# Generated by Django 5.2.15 on 2026-06-16 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentinstance_customer_and_more"),
        ("inventory", "0004_inventoryavailability_hahitantsoa_event_draft"),
        ("reservations", "0006_reservationdraft_prerequisite_marker_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryStockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("outbound_delivery", "outbound_delivery"),
                            ("inbound_return", "inbound_return"),
                            ("damage", "damage"),
                            ("loss", "loss"),
                            ("adjustment_in", "adjustment_in"),
                            ("adjustment_out", "adjustment_out"),
                            ("other", "other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "inbound"), ("outbound", "outbound")],
                        max_length=16,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("source_label", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("effective_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("validated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_stock_movements",
                        to="documents.documentinstance",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "reservation_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="reservations.reservationdraft",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory stock movement",
                "verbose_name_plural": "Inventory stock movements",
                "ordering": ["-effective_at", "-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="inventory_stock_movement_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("direction__in", ["inbound", "outbound"]),
                                ("movement_type", "other"),
                            ),
                            models.Q(("movement_type", "other"), _negated=True),
                            _connector="OR",
                        ),
                        name="inventory_stock_movement_other_requires_direction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reservation_draft__isnull", False),
                            ("document_instance__isnull", False),
                            models.Q(
                                models.Q(("source_label", ""), _negated=True),
                                models.Q(("notes", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="inventory_stock_movement_standalone_requires_source_and_notes",
                    ),
                ],
            },
        ),
    ]
