# Generated by Django 5.2.15 on 2026-06-17 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentinstance_customer_and_more'),
        ('inventory', '0005_inventorystockmovement'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReturnOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('validated', 'validated')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_operations', to='documents.documentinstance')),
                ('reservation_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_operations', to='reservations.reservationdraft')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory return operation',
                'verbose_name_plural': 'Inventory return operations',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inventorystockmovement',
            name='return_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventoryreturnoperation'),
        ),
        migrations.CreateModel(
            name='InventoryReturnOperationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.PositiveIntegerField()),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('missing_quantity', models.PositiveIntegerField(default=0)),
                ('condition_status', models.CharField(choices=[('intact', 'intact'), ('damaged', 'damaged'), ('missing', 'missing'), ('mixed', 'mixed')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_operation_lines', to='inventory.inventoryitem')),
                ('return_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryreturnoperation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory return operation line',
                'verbose_name_plural': 'Inventory return operation lines',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inventorystockmovement',
            name='return_operation_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventoryreturnoperationline'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('validated_at__isnull', True)), models.Q(('status', 'validated'), ('validated_at__isnull', False)), _connector='OR'), name='inventory_return_operation_status_validated_at_consistent'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperationline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gt', 0)), name='inventory_return_operation_line_expected_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperationline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0)), name='inventory_return_operation_line_returned_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperationline',
            constraint=models.CheckConstraint(condition=models.Q(('damaged_quantity__gte', 0)), name='inventory_return_operation_line_damaged_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperationline',
            constraint=models.CheckConstraint(condition=models.Q(('missing_quantity__gte', 0)), name='inventory_return_operation_line_missing_quantity_non_negative'),
        ),
    ]
