# Generated by Django 5.2.15 on 2026-06-17 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentinstance_customer_and_more'),
        ('inventory', '0006_inventoryreturnoperation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDamageLossSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_status', models.CharField(choices=[('draft', 'draft'), ('validated', 'validated'), ('cancelled', 'cancelled')], default='draft', max_length=32)),
                ('damage_loss_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_available', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excess_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_loss_settlements', to='documents.documentinstance')),
                ('return_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='damage_loss_settlement', to='inventory.inventoryreturnoperation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory damage/loss settlement',
                'verbose_name_plural': 'Inventory damage/loss settlements',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDamageLossSettlementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_label', models.CharField(blank=True, max_length=255)),
                ('settlement_line_kind', models.CharField(choices=[('damage', 'damage'), ('loss', 'loss'), ('repair', 'repair'), ('non_inventory_damage', 'non_inventory_damage'), ('other', 'other')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_source', models.CharField(choices=[('manual', 'manual'), ('inventory_default', 'inventory_default'), ('pricing_table', 'pricing_table'), ('override', 'override')], default='manual', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('return_operation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_loss_settlement_lines', to='inventory.inventoryreturnoperationline')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorydamagelosssettlement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory damage/loss settlement line',
                'verbose_name_plural': 'Inventory damage/loss settlement lines',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(('damage_loss_total__gte', 0)), name='inventory_damage_loss_settlement_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(('caution_available__gte', 0)), name='inventory_damage_loss_settlement_caution_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(('caution_applied__gte', 0)), name='inventory_damage_loss_settlement_caution_applied_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(('refund_due__gte', 0)), name='inventory_damage_loss_settlement_refund_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(('excess_due__gte', 0)), name='inventory_damage_loss_settlement_excess_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settlement_status', 'draft'), ('validated_at__isnull', True), ('validated_by__isnull', True)), models.Q(('settlement_status', 'cancelled'), ('validated_at__isnull', True), ('validated_by__isnull', True)), models.Q(('settlement_status', 'validated'), ('validated_at__isnull', False), ('validated_by__isnull', False)), _connector='OR'), name='inventory_damage_loss_settlement_status_marker_consistent'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_damage_loss_settlement_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gt', 0)), name='inventory_damage_loss_settlement_line_unit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='inventory_damage_loss_settlement_line_total_amount_non_negative'),
        ),
    ]
