# Generated by Django 5.2.17 on 2026-08-27 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_documentinstance_customer_contact_points_snapshot'),
        ('hahitantsoa', '0012_alter_hahitantsoaservice_image_url'),
        ('inventory', '0007_hahitantsoa_event_draft_stock'),
        ('logistics', '0007_hahitantsoa_event_draft'),
        ('reservations', '0010_reservationdraftamendment_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreturnoperation',
            name='hahitantsoa_event_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_operations', to='hahitantsoa.hahitantsoaeventdraft'),
        ),
        migrations.AddField(
            model_name='inventoryreturnoperation',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=96),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperation',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', True), ('hahitantsoa_event_draft__isnull', True), _connector='OR'), name='inventory_return_operation_single_business_draft'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_draft__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('reservation_draft', 'idempotency_key'), name='inventory_return_operation_titan_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreturnoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('hahitantsoa_event_draft__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('hahitantsoa_event_draft', 'idempotency_key'), name='inventory_return_operation_hahitantsoa_idempotency_key_unique'),
        ),
    ]
