# Generated by Django 5.2.15 on 2026-06-17 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorydamagelosssettlement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDamageLossSettlementExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('executed', 'executed'), ('cancelled', 'cancelled')], default='draft', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('damage_loss_total_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_available_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_applied_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_due_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excess_due_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='inventory.inventorydamagelosssettlement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory damage/loss settlement execution',
                'verbose_name_plural': 'Inventory damage/loss settlement executions',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDamageLossExcessReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_invoice', 'pending_invoice'), ('invoiced', 'invoiced'), ('cancelled', 'cancelled')], default='pending_invoice', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement_execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='excess_receivable', to='inventory.inventorydamagelosssettlementexecution')),
            ],
            options={
                'verbose_name': 'Inventory damage/loss excess receivable',
                'verbose_name_plural': 'Inventory damage/loss excess receivables',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCautionRefundObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('settled', 'settled'), ('cancelled', 'cancelled')], default='pending', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement_execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_obligation', to='inventory.inventorydamagelosssettlementexecution')),
            ],
            options={
                'verbose_name': 'Inventory caution refund obligation',
                'verbose_name_plural': 'Inventory caution refund obligations',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(('damage_loss_total_snapshot__gte', 0)), name='inventory_damage_loss_execution_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(('caution_available_snapshot__gte', 0)), name='inventory_damage_loss_execution_caution_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(('caution_applied_snapshot__gte', 0)), name='inventory_damage_loss_execution_caution_applied_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(('refund_due_snapshot__gte', 0)), name='inventory_damage_loss_execution_refund_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(('excess_due_snapshot__gte', 0)), name='inventory_damage_loss_execution_excess_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelosssettlementexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('executed_at__isnull', True), ('executed_by__isnull', True)), models.Q(('status', 'cancelled'), ('executed_at__isnull', True), ('executed_by__isnull', True)), models.Q(('status', 'executed'), ('executed_at__isnull', False), ('executed_by__isnull', False)), _connector='OR'), name='inventory_damage_loss_execution_status_marker_consistent'),
        ),
        migrations.AddConstraint(
            model_name='inventorydamagelossexcessreceivable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inventory_damage_loss_excess_receivable_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorycautionrefundobligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inventory_caution_refund_obligation_amount_positive'),
        ),
    ]
