# Generated by Django 5.2.15 on 2026-06-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorydamagelosssettlementexecution_and_more'),
        ('logistics', '0002_alter_logisticsevent_event_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreturnoperation',
            name='logistics_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_operations', to='logistics.logisticsevent'),
        ),
    ]
