# Generated by Django 5.2.17 on 2026-08-12 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'À valider'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('validation_note', models.TextField(blank=True, default='')),
                ('irsa_brackets', models.JSONField(blank=True, default=list)),
                ('irsa_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('irsa_abatement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dependent_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('contribution_base_definition', models.TextField(blank=True, default='')),
                ('cnaps_employee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('cnaps_employer_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ostie_employee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ostie_employer_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fmfp_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('contribution_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('overtime_rules', models.JSONField(blank=True, default=dict)),
                ('payslip_contexture', models.JSONField(blank=True, default=dict)),
                ('dns_format', models.JSONField(blank=True, default=dict)),
                ('ostie_format', models.JSONField(blank=True, default=dict)),
                ('collective_agreement', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jeu de règles de paie',
                'verbose_name_plural': 'Jeux de règles de paie',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
