# Generated by Django 5.2.17 on 2026-08-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0002_payrollruleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='payroll_rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr_payroll.payrollruleset'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_rule_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
