# Generated by Django 5.2.17 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_payroll", "0003_payslip_payroll_rule_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payslips",
                to="hr_payroll.employee",
            ),
        ),
    ]
