# Generated by Django 5.2.17 on 2026-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0004_protect_payslip_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollruleset',
            name='field_confirmations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
