# Generated by Django 5.2.15 on 2026-06-12 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("reservations", "0003_reservationdraft_confirmation_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservationdraft",
            name="reservation_draft_status_allowed",
        ),
        migrations.AddConstraint(
            model_name="reservationdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "confirmed"])),
                name="reservation_draft_status_allowed",
            ),
        ),
    ]
