# Generated by Django 5.2.17 on 2026-08-28 19:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontactpoint'),
        ('inventory', '0008_inventoryreturnoperation_hahitantsoa_event_draft_and_more'),
        ('reservations', '0010_reservationdraftamendment_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdraft',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='discount_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='reservationdraftline',
            name='unit_rental_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='reservationdraft',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0), ('delivery_fee__gte', 0), ('discount_amount__gte', 0), ('total_amount__gte', 0)), name='reservation_draft_commercial_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reservationdraftline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rental_price__gte', 0)), name='reservation_draft_line_unit_rental_price_nonnegative'),
        ),
    ]
