# Generated by Django 5.2.17 on 2026-08-28 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontactpoint'),
        ('reservations', '0011_commercial_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdraft',
            name='discount_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationdraft',
            name='discount_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reservationdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_amount', 0), ('discount_applied_at__isnull', True), ('discount_applied_by__isnull', True)), models.Q(('discount_amount__gt', 0), ('discount_applied_at__isnull', False), ('discount_applied_by__isnull', False)), _connector='OR'), name='reservation_draft_discount_attribution_complete'),
        ),
    ]
