# Generated by Django 5.2.17 on 2026-08-31

from decimal import Decimal

from django.db import migrations, models


def backfill_required_deposit_amount(apps, schema_editor):
    ReservationDraft = apps.get_model("reservations", "ReservationDraft")
    for reservation_draft in ReservationDraft.objects.iterator():
        required_deposit_amount = (reservation_draft.total_amount * Decimal("0.25")).quantize(
            Decimal("0.01")
        )
        ReservationDraft.objects.filter(pk=reservation_draft.pk).update(
            required_deposit_amount=required_deposit_amount
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_commercial_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationdraft",
            name="required_deposit_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
        ),
        migrations.RunPython(backfill_required_deposit_amount, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reservationdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_deposit_amount__gte", 0)),
                name="reservation_draft_required_deposit_amount_nonnegative",
            ),
        ),
    ]
