# Generated by Django 5.2.15 on 2026-06-15 09:03

import apps.hahitantsoa.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0003_inventoryavailability_reservation_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaEventDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_reference', models.CharField(default=apps.hahitantsoa.models.generate_hahitantsoa_event_draft_public_reference, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft')], default='draft', max_length=32)),
                ('event_name', models.CharField(max_length=255)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('location_details', models.TextField(blank=True)),
                ('service_notes', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hahitantsoa_event_drafts', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hahitantsoa event draft',
                'verbose_name_plural': 'Hahitantsoa event drafts',
                'ordering': ['-created_at', 'public_reference'],
            },
        ),
        migrations.CreateModel(
            name='HahitantsoaEventDraftLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hahitantsoa.hahitantsoaeventdraft')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hahitantsoa_event_draft_lines', to='inventory.inventoryitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hahitantsoa event draft line',
                'verbose_name_plural': 'Hahitantsoa event draft lines',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft'])), name='hahitantsoa_event_draft_status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='hahitantsoa_event_draft_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraftline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='hahitantsoa_event_draft_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraftline',
            constraint=models.UniqueConstraint(fields=('event_draft', 'inventory_item'), name='hahitantsoa_event_draft_line_unique_item'),
        ),
    ]
