# Generated by Django 5.2.17 on 2026-08-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0006_add_venue_and_service_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Mariage'), ('engagement', 'Fiançailles'), ('civil_wedding', 'Mariage civil'), ('other', 'Autre')], default='other', max_length=32),
        ),
    ]
