# Generated by Django 5.2.17 on 2026-08-20 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_hahitantsoa_commercial_terms(apps, schema_editor):
    HahitantsoaCommercialTerms = apps.get_model("hahitantsoa", "HahitantsoaCommercialTerms")
    HahitantsoaCommercialTerms.objects.get_or_create(key="default")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontactpoint'),
        ('hahitantsoa', '0008_amendment_request_versioning'),
        ('inventory', '0007_hahitantsoa_event_draft_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaCommercialTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('base_space_rental_amount', models.DecimalField(decimal_places=2, default=6500000, max_digits=14)),
                ('included_guest_count', models.PositiveIntegerField(default=250)),
                ('excess_guest_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('bare_deposit_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=14)),
                ('logistics_deposit_amount', models.DecimalField(decimal_places=2, default=1500000, max_digits=14)),
            ],
            options={
                'verbose_name': 'Hahitantsoa commercial terms',
                'verbose_name_plural': 'Hahitantsoa commercial terms',
            },
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='rental_type',
            field=models.CharField(choices=[('bare', 'Location nue'), ('logistics', 'Location + logistique')], default='bare', max_length=16),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='required_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='space_rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraftline',
            name='unit_rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('rental_type__in', ['bare', 'logistics'])), name='hahitantsoa_event_draft_rental_type_allowed'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('space_rental_amount__gte', 0)), name='hahitantsoa_event_draft_space_rental_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('required_deposit_amount__gte', 0)), name='hahitantsoa_event_draft_required_deposit_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraftline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rental_price__gte', 0)), name='hahitantsoa_event_draft_line_unit_rental_price_nonnegative'),
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('base_space_rental_amount__gte', 0)), name='hahitantsoa_terms_base_space_rental_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('excess_guest_amount__gte', 0)), name='hahitantsoa_terms_excess_guest_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('bare_deposit_amount__gte', 0)), name='hahitantsoa_terms_bare_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('logistics_deposit_amount__gte', 0)), name='hahitantsoa_terms_logistics_deposit_nonnegative'),
        ),
        migrations.RunPython(
            create_default_hahitantsoa_commercial_terms,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
