# Generated by Django 5.2.17 on 2026-08-26 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0009_hahitantsoacommercialterms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hahitantsoaservice',
            options={'ordering': ['category', 'name', 'id'], 'verbose_name': 'Hahitantsoa service', 'verbose_name_plural': 'Hahitantsoa services'},
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='caution_amount',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='night_option_1_amount',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='night_option_2_amount',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoacommercialterms',
            name='night_security_amount',
            field=models.DecimalField(decimal_places=2, default=120000, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='category',
            field=models.CharField(choices=[('drapery', 'Draperie & Voilage'), ('starry_sky', 'Ciel étoilé'), ('scenography', 'Piste & Scénographie'), ('special_effects', 'Effets spéciaux'), ('technical_facility', 'Prestations techniques & Aménagement'), ('other', 'Autre prestation')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='is_external_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='pricing_type',
            field=models.CharField(choices=[('flat_fee', 'Forfait'), ('per_line', 'À la ligne'), ('per_unit', 'Unitaire'), ('on_quote', 'Sur devis')], default='flat_fee', max_length=16),
        ),
        migrations.AddField(
            model_name='hahitantsoaservice',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('night_option_1_amount__gte', 0)), name='hahitantsoa_terms_night_option_1_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('night_option_2_amount__gte', 0)), name='hahitantsoa_terms_night_option_2_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('night_security_amount__gte', 0)), name='hahitantsoa_terms_night_security_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoacommercialterms',
            constraint=models.CheckConstraint(condition=models.Q(('caution_amount__gte', 0)), name='hahitantsoa_terms_caution_amount_nonnegative'),
        ),
    ]
