# Generated by Django 5.2.17 on 2026-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0011_seed_hahitantsoa_services_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahitantsoaservice',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
