# Generated by Django 5.2.17 on 2026-08-28 23:47

from django.conf import settings
from django.db import migrations, models


def backfill_commercial_totals(apps, schema_editor):
    event_draft_model = apps.get_model("hahitantsoa", "HahitantsoaEventDraft")
    line_model = apps.get_model("hahitantsoa", "HahitantsoaEventDraftLine")
    for event_draft in event_draft_model.objects.all().iterator():
        logistics_amount = sum(
            (
                line.unit_rental_price * line.quantity
                for line in line_model.objects.filter(
                    event_draft_id=event_draft.id, is_deleted=False
                )
            ),
            0,
        )
        event_draft.logistics_amount = logistics_amount
        event_draft.total_amount = event_draft.space_rental_amount + logistics_amount
        event_draft.save(update_fields=["logistics_amount", "total_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontactpoint'),
        ('hahitantsoa', '0012_alter_hahitantsoaservice_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='logistics_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.RunPython(backfill_commercial_totals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('logistics_amount__gte', 0)), name='hahitantsoa_event_draft_logistics_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='hahitantsoa_event_draft_total_amount_nonnegative'),
        ),
    ]
