# Generated by Django 5.2.17 on 2026-08-29 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0013_hahitantsoaeventdraft_logistics_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaEventCloseout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'closed')], default='closed', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('signature_exception_reason', models.TextField(blank=True)),
                ('summary_snapshot', models.JSONField(default=dict)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hahitantsoa_event_closeouts', to=settings.AUTH_USER_MODEL)),
                ('event_draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closeout_record', to='hahitantsoa.hahitantsoaeventdraft')),
            ],
            options={
                'verbose_name': 'Hahitantsoa event closeout',
                'verbose_name_plural': 'Hahitantsoa event closeouts',
                'ordering': ['-closed_at', '-created_at', 'id'],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION hahitantsoa_prevent_closeout_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'Hahitantsoa event closeouts are append-only.';
                END;
                $$;

                CREATE TRIGGER hahitantsoa_event_closeout_append_only
                BEFORE UPDATE OR DELETE ON hahitantsoa_hahitantsoaeventcloseout
                FOR EACH ROW
                EXECUTE FUNCTION hahitantsoa_prevent_closeout_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS hahitantsoa_event_closeout_append_only
                ON hahitantsoa_hahitantsoaeventcloseout;
                DROP FUNCTION IF EXISTS hahitantsoa_prevent_closeout_mutation();
            """,
        ),
    ]
