# Generated by Django 5.2.17 on 2026-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0015_event_draft_venue_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahitantsoaeventdraftamendmentrequest',
            name='changed_guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraftamendmentrequest',
            name='changed_rental_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraftamendmentrequest',
            name='changed_space_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
