# Generated by Django 5.2.17 on 2026-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0016_hahitantsoaeventdraftamendmentrequest_changed_guest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='duration_option',
            field=models.CharField(
                choices=[
                    ('day', 'Fête de jour'),
                    ('night_1', 'Utilisation de nuit Option 1'),
                    ('night_2', 'Utilisation de nuit Option 2'),
                ],
                default='day',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraftamendmentrequest',
            name='changed_duration_option',
            field=models.CharField(
                blank=True,
                choices=[
                    ('day', 'Fête de jour'),
                    ('night_1', 'Utilisation de nuit Option 1'),
                    ('night_2', 'Utilisation de nuit Option 2'),
                ],
                max_length=16,
            ),
        ),
    ]
