# Generated by Django 5.2.17 on 2026-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0017_hahitantsoaeventdraft_duration_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahitantsoaeventdraft',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Mariage'), ('engagement', 'Fiançailles'), ('civil_wedding', 'Mariage civil'), ('baptism', 'Baptême'), ('birthday', 'Anniversaire'), ('reception', 'Réception privée'), ('seminar', 'Séminaire'), ('corporate', 'Corporate'), ('conference', 'Conférence'), ('workshop', 'Atelier / Formation'), ('family', 'Fête familiale'), ('other', 'Autre')], default='other', max_length=32),
        ),
    ]
