# Generated by Django 5.2.17 on 2026-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0018_expand_event_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahitantsoaeventdraftamendmentrequest',
            name='changed_service_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
