# Generated by Django 5.2.17 on 2026-09-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customercontactpoint'),
        ('hahitantsoa', '0019_alter_hahitantsoaeventdraftamendmentrequest_changed_service_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hahitantsoaeventdraft',
            name='hahitantsoa_event_draft_status_allowed',
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hahitantsoaeventdraft',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hahitantsoaeventdraft',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('archived', 'archived')], default='draft', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'confirmed', 'cancelled', 'archived'])), name='hahitantsoa_event_draft_status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='hahitantsoaeventdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False)), _connector='OR'), name='hahitantsoa_event_draft_cancelled_marker_complete'),
        ),
    ]
