# Generated by Django 5.2.17 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0020_remove_hahitantsoaeventdraft_hahitantsoa_event_draft_status_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahitantsoacommercialterms',
            name='night_security_amount',
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=14),
        ),
    ]
