# Generated by Django 5.2.15 on 2026-06-19 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservations", "0006_reservationdraft_prerequisite_marker_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(choices=[("delivery", "delivery"), ("pickup", "pickup")], max_length=32)),
                ("status", models.CharField(choices=[("planned", "planned"), ("dispatched", "dispatched"), ("completed", "completed"), ("cancelled", "cancelled")], default="planned", max_length=32)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("reservation_draft", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="logistics_events", to="reservations.reservationdraft")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Logistics Event",
                "verbose_name_plural": "Logistics Events",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
    ]
