# Generated by Django 5.2.15 on 2026-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsevent',
            name='event_type',
            field=models.CharField(choices=[('delivery', 'delivery'), ('pickup', 'pickup'), ('preparation', 'preparation'), ('handover', 'handover')], max_length=32),
        ),
    ]
