# Generated by Django 5.2.16 on 2026-08-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_logisticsevent_passation_signature_and_item_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsevent',
            name='signature_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logisticsevent',
            name='signature_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente de signature'), ('received', 'Document signé reçu'), ('exception', 'Signature exceptionnellement non obtenue')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='logisticsevent',
            name='signed_by_client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='logisticsevent',
            name='signed_document_file',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='logisticsevent',
            name='signed_document_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
