# Generated by Django 5.2.14 on 2026-07-20 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('payment', 'payment'), ('stock', 'stock'), ('import', 'import'), ('reservation', 'reservation'), ('system', 'system')], default='system', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('success', 'success'), ('error', 'error')], default='info', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System notification',
                'verbose_name_plural': 'System notifications',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
