# Generated by Django 5.2.17 on 2026-08-13 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahitantsoa', '0008_amendment_request_versioning'),
        ('notifications', '0001_initial'),
        ('reservations', '0010_reservationdraftamendment_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_key', models.CharField(max_length=96)),
                ('message', models.TextField()),
                ('whatsapp_url', models.TextField(blank=True, default='')),
                ('prepared_at', models.DateTimeField()),
                ('hahitantsoa_event_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminder_dispatches', to='hahitantsoa.hahitantsoaeventdraft')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('reservation_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminder_dispatches', to='reservations.reservationdraft')),
            ],
            options={
                'ordering': ['-prepared_at', '-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', True)), models.Q(('reservation_draft__isnull', True), ('hahitantsoa_event_draft__isnull', False)), _connector='OR'), name='payment_reminder_single_draft_link'), models.UniqueConstraint(condition=models.Q(('reservation_draft__isnull', False)), fields=('reservation_draft', 'reminder_key'), name='payment_reminder_reservation_key_unique'), models.UniqueConstraint(condition=models.Q(('hahitantsoa_event_draft__isnull', False)), fields=('hahitantsoa_event_draft', 'reminder_key'), name='payment_reminder_hahitantsoa_key_unique')],
            },
        ),
    ]
