from django.urls import path

from apps.reservations.views import (
    ReservationAvailabilitySummaryAPIView,
    ReservationAvailableItemPreviewsAPIView,
    ReservationDraftAmendmentListCreateAPIView,
    ReservationDraftCancelAPIView,
    ReservationDraftCloseoutExecuteAPIView,
    ReservationDraftCloseoutSummaryAPIView,
    ReservationDraftConfirmAPIView,
    ReservationDraftLifecycleAPIView,
    ReservationDraftListCreateAPIView,
    ReservationDraftMarkContractSignedAPIView,
    ReservationDraftMarkRequiredDepositReceivedAPIView,
    ReservationDraftRetrieveAPIView,
    ReservationDraftSoftDeleteAPIView,
    ReservationItemAvailabilityPreviewAPIView,
)

urlpatterns = [
    path(
        "api/v1/reservations/drafts/<uuid:pk>/lifecycle/",
        ReservationDraftLifecycleAPIView.as_view(),
        name="reservation-draft-lifecycle",
    ),
    path(
        "api/v1/reservations/drafts/",
        ReservationDraftListCreateAPIView.as_view(),
        name="reservation-draft-list",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/",
        ReservationDraftRetrieveAPIView.as_view(),
        name="reservation-draft-detail",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/amendments/",
        ReservationDraftAmendmentListCreateAPIView.as_view(),
        name="reservation-draft-amendment-list-create",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/confirm/",
        ReservationDraftConfirmAPIView.as_view(),
        name="reservation-draft-confirm",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/cancel/",
        ReservationDraftCancelAPIView.as_view(),
        name="reservation-draft-cancel",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/delete/",
        ReservationDraftSoftDeleteAPIView.as_view(),
        name="reservation-draft-soft-delete",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/contract-signed/",
        ReservationDraftMarkContractSignedAPIView.as_view(),
        name="reservation-draft-mark-contract-signed",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/required-deposit-received/",
        ReservationDraftMarkRequiredDepositReceivedAPIView.as_view(),
        name="reservation-draft-mark-required-deposit-received",
    ),
    path(
        "api/v1/reservations/availability-summary/",
        ReservationAvailabilitySummaryAPIView.as_view(),
        name="reservation-availability-summary",
    ),
    path(
        "api/v1/reservations/available-item-previews/",
        ReservationAvailableItemPreviewsAPIView.as_view(),
        name="reservation-available-item-previews",
    ),
    path(
        "api/v1/reservations/items/<uuid:inventory_item_id>/availability-preview/",
        ReservationItemAvailabilityPreviewAPIView.as_view(),
        name="reservation-item-availability-preview",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/closeout/",
        ReservationDraftCloseoutSummaryAPIView.as_view(),
        name="reservation-draft-closeout-summary",
    ),
    path(
        "api/v1/reservations/drafts/<uuid:pk>/closeout/execute/",
        ReservationDraftCloseoutExecuteAPIView.as_view(),
        name="reservation-draft-closeout-execute",
    ),
]
