from django.urls import path

from apps.hahitantsoa.views import (
    HahitantsoaCommercialTermsAPIView,
    HahitantsoaDiscoveryItemsAPIView,
    HahitantsoaEventDraftAmendmentPreflightAPIView,
    HahitantsoaEventDraftAmendmentRequestApplyAPIView,
    HahitantsoaEventDraftAmendmentRequestAvailabilityPreflightAPIView,
    HahitantsoaEventDraftAmendmentRequestLineListCreateAPIView,
    HahitantsoaEventDraftAmendmentRequestLineRetrieveUpdateDestroyAPIView,
    HahitantsoaEventDraftAmendmentRequestListCreateAPIView,
    HahitantsoaEventDraftAmendmentRequestRetrieveUpdateAPIView,
    HahitantsoaEventDraftAvailabilityPreviewAPIView,
    HahitantsoaEventDraftCloseoutExecuteAPIView,
    HahitantsoaEventDraftCloseoutSummaryAPIView,
    HahitantsoaEventDraftConfirmAPIView,
    HahitantsoaEventDraftConfirmationPreflightAPIView,
    HahitantsoaEventDraftDocumentInstanceGenerateAPIView,
    HahitantsoaEventDraftDocumentInstanceGeneratePdfAPIView,
    HahitantsoaEventDraftDocumentInstanceListCreateAPIView,
    HahitantsoaEventDraftDocumentInstanceRetrieveAPIView,
    HahitantsoaEventDraftDocumentPreviewAPIView,
    HahitantsoaEventDraftLifecycleAPIView,
    HahitantsoaEventDraftListCreateAPIView,
    HahitantsoaEventDraftMarkContractSignedAPIView,
    HahitantsoaEventDraftMarkRequiredDepositReceivedAPIView,
    HahitantsoaEventDraftRetrieveUpdateAPIView,
    HahitantsoaServiceListCreateAPIView,
    HahitantsoaServiceRetrieveUpdateDestroyAPIView,
    HahitantsoaSharedAvailabilityAPIView,
    HahitantsoaVenueListCreateAPIView,
    HahitantsoaVenueOccupancyAPIView,
    HahitantsoaVenueRetrieveUpdateAPIView,
)

urlpatterns = [
    path(
        "event-drafts/<uuid:pk>/lifecycle/",
        HahitantsoaEventDraftLifecycleAPIView.as_view(),
        name="hahitantsoa-event-draft-lifecycle",
    ),
    path(
        "commercial-terms/",
        HahitantsoaCommercialTermsAPIView.as_view(),
        name="hahitantsoa-commercial-terms",
    ),
    path(
        "discovery-items/",
        HahitantsoaDiscoveryItemsAPIView.as_view(),
        name="hahitantsoa-discovery-items",
    ),
    path(
        "shared-availability/",
        HahitantsoaSharedAvailabilityAPIView.as_view(),
        name="hahitantsoa-shared-availability",
    ),
    path(
        "venue-occupancy/",
        HahitantsoaVenueOccupancyAPIView.as_view(),
        name="hahitantsoa-venue-occupancy",
    ),
    path(
        "event-drafts/",
        HahitantsoaEventDraftListCreateAPIView.as_view(),
        name="hahitantsoa-event-draft-list",
    ),
    path(
        "event-drafts/<uuid:pk>/",
        HahitantsoaEventDraftRetrieveUpdateAPIView.as_view(),
        name="hahitantsoa-event-draft-detail",
    ),
    path(
        "event-drafts/<uuid:pk>/availability-preview/",
        HahitantsoaEventDraftAvailabilityPreviewAPIView.as_view(),
        name="hahitantsoa-event-draft-availability-preview",
    ),
    path(
        "event-drafts/<uuid:pk>/confirmation-preflight/",
        HahitantsoaEventDraftConfirmationPreflightAPIView.as_view(),
        name="hahitantsoa-event-draft-confirmation-preflight",
    ),
    path(
        "event-drafts/<uuid:pk>/amendment-preflight/",
        HahitantsoaEventDraftAmendmentPreflightAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-preflight",
    ),
    path(
        "event-drafts/<uuid:event_draft_pk>/amendment-requests/",
        HahitantsoaEventDraftAmendmentRequestListCreateAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-list",
    ),
    path(
        "event-drafts/<uuid:event_draft_pk>/amendment-requests/<uuid:pk>/",
        HahitantsoaEventDraftAmendmentRequestRetrieveUpdateAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-detail",
    ),
    path(
        "event-drafts/<uuid:event_draft_pk>/amendment-requests/<uuid:pk>/apply/",
        HahitantsoaEventDraftAmendmentRequestApplyAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-apply",
    ),
    path(
        (
            "event-drafts/<uuid:event_draft_pk>/amendment-requests/"
            "<uuid:amendment_request_pk>/availability-preflight/"
        ),
        HahitantsoaEventDraftAmendmentRequestAvailabilityPreflightAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-availability-preflight",
    ),
    path(
        "event-drafts/<uuid:event_draft_pk>/amendment-requests/<uuid:amendment_request_pk>/lines/",
        HahitantsoaEventDraftAmendmentRequestLineListCreateAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-line-list",
    ),
    path(
        (
            "event-drafts/<uuid:event_draft_pk>/amendment-requests/"
            "<uuid:amendment_request_pk>/lines/<uuid:pk>/"
        ),
        HahitantsoaEventDraftAmendmentRequestLineRetrieveUpdateDestroyAPIView.as_view(),
        name="hahitantsoa-event-draft-amendment-request-line-detail",
    ),
    path(
        "event-drafts/<uuid:pk>/confirm/",
        HahitantsoaEventDraftConfirmAPIView.as_view(),
        name="hahitantsoa-event-draft-confirm",
    ),
    path(
        "event-drafts/<uuid:pk>/contract-signed/",
        HahitantsoaEventDraftMarkContractSignedAPIView.as_view(),
        name="hahitantsoa-event-draft-mark-contract-signed",
    ),
    path(
        "event-drafts/<uuid:pk>/required-deposit-received/",
        HahitantsoaEventDraftMarkRequiredDepositReceivedAPIView.as_view(),
        name="hahitantsoa-event-draft-mark-required-deposit-received",
    ),
    path(
        "event-drafts/<uuid:pk>/closeout/",
        HahitantsoaEventDraftCloseoutSummaryAPIView.as_view(),
        name="hahitantsoa-event-draft-closeout-summary",
    ),
    path(
        "event-drafts/<uuid:pk>/closeout/execute/",
        HahitantsoaEventDraftCloseoutExecuteAPIView.as_view(),
        name="hahitantsoa-event-draft-closeout-execute",
    ),
    path(
        "event-drafts/<uuid:pk>/documents/",
        HahitantsoaEventDraftDocumentInstanceListCreateAPIView.as_view(),
        name="hahitantsoa-event-draft-document-list",
    ),
    path(
        "event-drafts/<uuid:pk>/documents/preview/",
        HahitantsoaEventDraftDocumentPreviewAPIView.as_view(),
        name="hahitantsoa-event-draft-document-preview",
    ),
    path(
        "event-drafts/<uuid:pk>/documents/<uuid:id>/",
        HahitantsoaEventDraftDocumentInstanceRetrieveAPIView.as_view(),
        name="hahitantsoa-event-draft-document-detail",
    ),
    path(
        "event-drafts/<uuid:pk>/documents/<uuid:id>/generate/",
        HahitantsoaEventDraftDocumentInstanceGenerateAPIView.as_view(),
        name="hahitantsoa-event-draft-document-generate",
    ),
    path(
        "event-drafts/<uuid:pk>/documents/<uuid:id>/generate-pdf/",
        HahitantsoaEventDraftDocumentInstanceGeneratePdfAPIView.as_view(),
        name="hahitantsoa-event-draft-document-generate-pdf",
    ),
    path(
        "venues/",
        HahitantsoaVenueListCreateAPIView.as_view(),
        name="hahitantsoa-venue-list",
    ),
    path(
        "venues/<uuid:pk>/",
        HahitantsoaVenueRetrieveUpdateAPIView.as_view(),
        name="hahitantsoa-venue-detail",
    ),
    path(
        "services/",
        HahitantsoaServiceListCreateAPIView.as_view(),
        name="hahitantsoa-service-list",
    ),
    path(
        "services/<uuid:pk>/",
        HahitantsoaServiceRetrieveUpdateDestroyAPIView.as_view(),
        name="hahitantsoa-service-detail",
    ),
]
