# Generated by Django 5.2.15 on 2026-06-18 18:30

import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0003_alter_documentinstance_customer_and_more"),
        ("inventory", "0008_inventorydamagelosssettlementexecution_and_more"),
        ("payments", "0001_initial"),
        ("reservations", "0006_reservationdraft_prerequisite_marker_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            (
                                "inventory_damage_loss_excess_receivable",
                                "inventory_damage_loss_excess_receivable",
                            )
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("settled", "settled"),
                            ("cancelled", "cancelled"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issued_at", models.DateTimeField()),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoice",
                        to="documents.documentinstance",
                    ),
                ),
                (
                    "excess_receivable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoice",
                        to="inventory.inventorydamagelossexcessreceivable",
                    ),
                ),
                (
                    "reservation_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoices",
                        to="reservations.reservationdraft",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing invoice",
                "verbose_name_plural": "Billing invoices",
                "ordering": ["-issued_at", "-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="billing_invoice_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invoice_status", "open"),
                                ("settled_at__isnull", True),
                                ("settled_by__isnull", True),
                            ),
                            models.Q(
                                ("invoice_status", "cancelled"),
                                ("settled_at__isnull", True),
                                ("settled_by__isnull", True),
                            ),
                            models.Q(
                                ("invoice_status", "settled"),
                                ("settled_at__isnull", False),
                                ("settled_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="billing_invoice_status_markers_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingInvoiceSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("settled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement",
                        to="billing.billinginvoice",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoice_settlement",
                        to="payments.payment",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing invoice settlement",
                "verbose_name_plural": "Billing invoice settlements",
                "ordering": ["-settled_at", "-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="billing_invoice_settlement_amount_positive",
                    )
                ],
            },
        ),
    ]
