# Generated by Django 5.2.15 on 2026-06-21 04:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('payments', '0003_remove_payment_payment_requires_reservation_or_source_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoiceInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('partially_paid', 'partially_paid'), ('paid', 'paid')], default='unpaid', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='billing.billinginvoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing invoice installment',
                'verbose_name_plural': 'Billing invoice installments',
                'ordering': ['due_at', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BillingInstallmentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_installment_allocation', to='payments.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.billinginvoiceinstallment')),
            ],
            options={
                'verbose_name': 'Billing installment allocation',
                'verbose_name_plural': 'Billing installment allocations',
                'ordering': ['-allocated_at', '-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billinginvoiceinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='billing_installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoiceinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', Decimal('0.00'))), name='billing_installment_paid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoiceinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('amount'))), name='billing_installment_paid_not_exceeds_amount'),
        ),
        migrations.AddConstraint(
            model_name='billinginvoiceinstallment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_amount', Decimal('0.00')), ('status', 'unpaid')), models.Q(('paid_amount__gt', Decimal('0.00')), ('paid_amount__lt', models.F('amount')), ('status', 'partially_paid')), models.Q(('paid_amount', models.F('amount')), ('status', 'paid')), _connector='OR'), name='billing_installment_status_paid_consistent'),
        ),
        migrations.AddConstraint(
            model_name='billinginstallmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='billing_installment_allocation_amount_positive'),
        ),
    ]
