# Generated by Django 5.2.15 on 2026-06-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_refund_obligation_execution_fields'),
        ('inventory', '0009_add_return_operation_logistics_event_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='excess_receivable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice', to='inventory.inventorydamagelossexcessreceivable'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='source_kind',
            field=models.CharField(choices=[('inventory_damage_loss_excess_receivable', 'inventory_damage_loss_excess_receivable'), ('commercial_closeout', 'commercial_closeout')], max_length=64),
        ),
    ]
