# Generated by Django 5.2.15 on 2026-06-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_commercial_closeout_source_kind'),
        ('documents', '0004_documentinstance_hahitantsoa_event_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='document_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice', to='documents.documentinstance'),
        ),
    ]
