# Generated by Django 5.2.15 on 2026-06-22 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_make_document_instance_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoiceNumberingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('inventory_damage_loss_excess_receivable', 'inventory_damage_loss_excess_receivable'), ('commercial_closeout', 'commercial_closeout')], max_length=64, unique=True)),
                ('prefix', models.CharField(default='FACT-', max_length=32)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('fiscal_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Billing invoice numbering policy',
                'verbose_name_plural': 'Billing invoice numbering policies',
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
