# Generated by Django 5.2.15 on 2026-06-22 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billing_credit_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingcreditnote',
            name='billing_credit_note_status_markers_consistent',
        ),
        migrations.AddConstraint(
            model_name='billingcreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', True), ('applied_by__isnull', True), ('status', 'issued')), models.Q(('applied_at__isnull', False), ('applied_by__isnull', False), ('status', 'applied')), models.Q(('applied_at__isnull', True), ('applied_by__isnull', True), ('status', 'cancelled')), _connector='OR'), name='billing_credit_note_status_markers_consistent'),
        ),
    ]
