# Generated by Django 5.2.16 on 2026-08-04 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBankProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=128)),
                ('rib', models.CharField(blank=True, max_length=128)),
                ('iban', models.CharField(blank=True, max_length=128)),
                ('swift_bic', models.CharField(blank=True, max_length=32)),
                ('is_default_for_documents', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_profile', to='finance.financeaccount')),
            ],
            options={
                'ordering': ['account__business_scope', 'bank_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('account',), name='finance_bank_profile_account_unique'), models.UniqueConstraint(condition=models.Q(('is_default_for_documents', True)), fields=('account',), name='finance_bank_profile_one_default_per_account')],
            },
        ),
    ]
