# Generated by Django 5.2.16 on 2026-08-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financebankprofile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financebankprofile',
            name='finance_bank_profile_account_unique',
        ),
        migrations.RemoveConstraint(
            model_name='financebankprofile',
            name='finance_bank_profile_one_default_per_account',
        ),
    ]
