from django.urls import path

from apps.documents.views import (
    DocumentInstancePDFRetrieveAPIView,
    DocumentInstancePrivateArtifactAPIView,
    DocumentTemplateDefinitionAPIView,
    DocumentTemplateRegistryAPIView,
    ReservationDraftDocumentInstanceGenerateAPIView,
    ReservationDraftDocumentInstanceListCreateAPIView,
    ReservationDraftDocumentInstancePDFGenerateAPIView,
    ReservationDraftDocumentInstanceRetrieveAPIView,
    TitanProformaDraftPreviewAPIView,
)

urlpatterns = [
    path(
        "templates/",
        DocumentTemplateRegistryAPIView.as_view(),
        name="document-template-registry",
    ),
    path(
        "templates/<str:template_key>/",
        DocumentTemplateDefinitionAPIView.as_view(),
        name="document-template-definition",
    ),
    path(
        "titan/proforma-drafts/<uuid:reservation_draft_id>/preview/",
        TitanProformaDraftPreviewAPIView.as_view(),
        name="titan-proforma-draft-preview",
    ),
    path(
        "instances/<uuid:id>/artifact/",
        DocumentInstancePrivateArtifactAPIView.as_view(),
        name="document-instance-private-artifact",
    ),
    path(
        "reservation-drafts/<uuid:reservation_draft_id>/instances/",
        ReservationDraftDocumentInstanceListCreateAPIView.as_view(),
        name="reservation-draft-document-instance-list",
    ),
    path(
        "reservation-drafts/<uuid:reservation_draft_id>/instances/<uuid:id>/",
        ReservationDraftDocumentInstanceRetrieveAPIView.as_view(),
        name="reservation-draft-document-instance-detail",
    ),
    path(
        "reservation-drafts/<uuid:reservation_draft_id>/instances/<uuid:id>/generate/",
        ReservationDraftDocumentInstanceGenerateAPIView.as_view(),
        name="reservation-draft-document-instance-generate",
    ),
    path(
        "reservation-drafts/<uuid:reservation_draft_id>/instances/<uuid:id>/generate-pdf/",
        ReservationDraftDocumentInstancePDFGenerateAPIView.as_view(),
        name="reservation-draft-document-instance-generate-pdf",
    ),
    path(
        "instances/<uuid:id>/pdf/",
        DocumentInstancePDFRetrieveAPIView.as_view(),
        name="document-instance-pdf-retrieve",
    ),
]
