# Generated by Django 5.2.16 on 2026-07-22 23:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        ('finance', '0002_financial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashboxsession',
            name='cashbox_single_open_session_per_operator',
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_sessions', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='cashboxsession',
            name='opening_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='cashboxsession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('operator', 'cash_account'), name='cashbox_single_open_session_per_operator_and_account'),
        ),
    ]
