# Generated by Django 5.2.16 on 2026-07-22 23:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_remove_cashboxsession_cashbox_single_open_session_per_operator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('count_submitted', 'Count submitted'), ('validated_closed', 'Validated closed'), ('reopened', 'Reopened')], default='open', max_length=32),
        ),
        migrations.CreateModel(
            name='CashboxClosureAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theoretical_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_justification', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField()),
                ('submission_idempotency_key', models.CharField(max_length=128)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_attempts', to='cashbox.cashboxsession')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('actual_amount__gte', Decimal('0.00'))), name='cashbox_closure_actual_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('variance_amount', Decimal('0.00')), models.Q(('variance_justification', ''), _negated=True), _connector='OR'), name='cashbox_closure_variance_requires_justification'), models.UniqueConstraint(fields=('session', 'submission_idempotency_key'), name='cashbox_closure_submission_idempotency_unique')],
            },
        ),
    ]
