# Generated by Django 5.2.16 on 2026-07-23 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_legacy_sessions_terminal(apps, schema_editor):
    """Quarantine pre-F2-2 rows without inventing closure evidence.

    ``cash_account IS NULL`` remains the durable marker for a pre-F2-2 session.
    No CashboxClosureAttempt or CashboxReopenEvent is fabricated for historical
    data; this gives every unassigned historical row a terminal lifecycle label.
    """

    CashboxSession = apps.get_model("cashbox", "CashboxSession")
    CashboxSession.objects.filter(cash_account__isnull=True).update(status="legacy_terminal")


def restore_legacy_session_statuses(apps, schema_editor):
    """Restore the pre-0004 default status for rows quarantined by this migration."""

    CashboxSession = apps.get_model("cashbox", "CashboxSession")
    CashboxSession.objects.filter(cash_account__isnull=True, status="legacy_terminal").update(
        status="open"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_cashboxsession_status_cashboxclosureattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('count_submitted', 'Count submitted'), ('validated_closed', 'Validated closed'), ('legacy_terminal', 'Legacy terminal')], default='open', max_length=32),
        ),
        migrations.RunPython(mark_legacy_sessions_terminal, restore_legacy_session_statuses),
        migrations.CreateModel(
            name='CashboxReopenEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('reopened_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('closure_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_events', to='cashbox.cashboxclosureattempt')),
                ('reopened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_events', to='cashbox.cashboxsession')),
            ],
            options={
                'ordering': ['-reopened_at', '-created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'idempotency_key'), name='cashbox_reopen_idempotency_unique')],
            },
        ),
    ]
