# Generated by Django 5.2.17 on 2026-08-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpackage',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
