# Generated by Django 5.2 on 2026-07-22

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_customer_lifecycle_status_customer_party_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitAppointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(choices=[("simple_visit", "Simple visite"), ("prospect", "Prospect"), ("other", "Autres")], max_length=32)),
                ("scheduled_at", models.DateTimeField()),
                ("location", models.CharField(default="Local de l'entreprise", max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("scheduled", "Planifiée"), ("completed", "Terminée"), ("cancelled", "Annulée")], default="scheduled", max_length=16)),
                ("reminder_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="visit_appointments", to="customers.customer")),
                ("responsible", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="responsible_visit_appointments", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Visit appointment", "verbose_name_plural": "Visit appointments", "ordering": ["scheduled_at", "created_at"]},
        ),
    ]
