from django.urls import path

from apps.inventory.views import (
    InventoryDamageLossSettlementExecutionExecuteAPIView,
    InventoryDamageLossSettlementExecutionListCreateAPIView,
    InventoryDamageLossSettlementExecutionRetrieveAPIView,
    InventoryDamageLossSettlementListCreateAPIView,
    InventoryDamageLossSettlementRetrieveAPIView,
    InventoryDamageLossSettlementValidateAPIView,
    InventoryItemListAPIView,
    InventoryItemRetrieveAPIView,
    InventoryReturnOperationListCreateAPIView,
    InventoryReturnOperationRetrieveAPIView,
    InventoryReturnOperationValidateAPIView,
    InventoryStockMovementListCreateAPIView,
    InventoryStockMovementRetrieveAPIView,
)

urlpatterns = [
    path(
        "api/v1/inventory/items/",
        InventoryItemListAPIView.as_view(),
        name="inventory-item-list",
    ),
    path(
        "api/v1/inventory/items/<uuid:pk>/",
        InventoryItemRetrieveAPIView.as_view(),
        name="inventory-item-detail",
    ),
    path(
        "api/v1/inventory/stock-movements/",
        InventoryStockMovementListCreateAPIView.as_view(),
        name="inventory-stock-movement-list",
    ),
    path(
        "api/v1/inventory/stock-movements/<uuid:id>/",
        InventoryStockMovementRetrieveAPIView.as_view(),
        name="inventory-stock-movement-detail",
    ),
    path(
        "api/v1/inventory/return-operations/",
        InventoryReturnOperationListCreateAPIView.as_view(),
        name="inventory-return-operation-list",
    ),
    path(
        "api/v1/inventory/return-operations/<uuid:id>/",
        InventoryReturnOperationRetrieveAPIView.as_view(),
        name="inventory-return-operation-detail",
    ),
    path(
        "api/v1/inventory/return-operations/<uuid:id>/validate/",
        InventoryReturnOperationValidateAPIView.as_view(),
        name="inventory-return-operation-validate",
    ),
    path(
        "api/v1/inventory/damage-loss-settlements/",
        InventoryDamageLossSettlementListCreateAPIView.as_view(),
        name="inventory-damage-loss-settlement-list",
    ),
    path(
        "api/v1/inventory/damage-loss-settlements/<uuid:id>/",
        InventoryDamageLossSettlementRetrieveAPIView.as_view(),
        name="inventory-damage-loss-settlement-detail",
    ),
    path(
        "api/v1/inventory/damage-loss-settlements/<uuid:id>/validate/",
        InventoryDamageLossSettlementValidateAPIView.as_view(),
        name="inventory-damage-loss-settlement-validate",
    ),
    path(
        "api/v1/inventory/damage-loss-settlement-executions/",
        InventoryDamageLossSettlementExecutionListCreateAPIView.as_view(),
        name="inventory-damage-loss-settlement-execution-list",
    ),
    path(
        "api/v1/inventory/damage-loss-settlement-executions/<uuid:id>/",
        InventoryDamageLossSettlementExecutionRetrieveAPIView.as_view(),
        name="inventory-damage-loss-settlement-execution-detail",
    ),
    path(
        "api/v1/inventory/damage-loss-settlement-executions/<uuid:id>/execute/",
        InventoryDamageLossSettlementExecutionExecuteAPIView.as_view(),
        name="inventory-damage-loss-settlement-execution-execute",
    ),
]
