# Generated by Django 5.2.15 on 2026-06-12 23:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("reservations", "0006_reservationdraft_prerequisite_marker_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_key", models.CharField(max_length=128)),
                ("template_version", models.CharField(max_length=32)),
                ("template_label", models.CharField(max_length=255)),
                ("business_scope", models.CharField(max_length=32)),
                ("document_type", models.CharField(max_length=128)),
                ("template_status", models.CharField(max_length=64)),
                ("template_source_kind", models.CharField(max_length=64)),
                ("template_source_reference", models.TextField()),
                ("template_path", models.CharField(max_length=512)),
                ("template_preview_path", models.CharField(max_length=512)),
                ("template_validated_by_client", models.BooleanField(default=False)),
                ("template_notes", models.TextField(blank=True)),
                ("reservation_public_reference", models.CharField(max_length=32)),
                ("reservation_status", models.CharField(max_length=32)),
                ("customer_display_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=64)),
                ("customer_address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "prepared"),
                            ("generated", "generated"),
                            ("issued", "issued"),
                            ("voided", "voided"),
                        ],
                        default="prepared",
                        max_length=32,
                    ),
                ),
                ("prepared_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("content_checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("storage_path", models.CharField(blank=True, max_length=512, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_instances",
                        to="customers.customer",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_instances",
                        to="reservations.reservationdraft",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document instance",
                "verbose_name_plural": "Document instances",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=["prepared", "generated", "issued", "voided"]
                        ),
                        name="document_instance_status_allowed",
                    ),
                    models.CheckConstraint(
                        condition=(
                            (
                                ~models.Q(status="voided")
                                & models.Q(voided_at__isnull=True)
                                & models.Q(voided_by__isnull=True)
                            )
                            | (
                                models.Q(status="voided")
                                & models.Q(voided_at__isnull=False)
                                & models.Q(voided_by__isnull=False)
                            )
                        ),
                        name="document_instance_voided_marker_consistent",
                    ),
                ],
            },
        ),
    ]
