# Generated by Django 5.2.15 on 2026-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='generated_content_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
