# Generated by Django 5.2.15 on 2026-06-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('documents', '0002_documentinstance_generated_content_size_bytes'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinstance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_instances', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='reservation_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_instances', to='reservations.reservationdraft'),
        ),
    ]
