# Generated by Django 5.2.15 on 2026-06-20 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('documents', '0003_alter_documentinstance_customer_and_more'),
        ('hahitantsoa', '0005_event_draft_amendment_request_line'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='hahitantsoa_event_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_instances', to='hahitantsoa.hahitantsoaeventdraft'),
        ),
        migrations.AddConstraint(
            model_name='documentinstance',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', False), _negated=True), name='document_instance_single_draft_link'),
        ),
    ]
