# Generated by Django 5.2.14 on 2026-06-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentinstance_hahitantsoa_event_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='pdf_content_checksum',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='pdf_storage_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
