# Generated by Django 5.2.14 on 2026-07-19 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_pdf_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('family', models.CharField(blank=True, default='', max_length=128)),
                ('business_scope', models.CharField(max_length=32)),
                ('document_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], default='draft', max_length=32)),
            ],
            options={
                'verbose_name': 'Document template',
                'verbose_name_plural': 'Document templates',
                'ordering': ['code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'archived'])), name='document_template_status_allowed')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], default='draft', max_length=32)),
                ('body_html', models.TextField(blank=True, default='')),
                ('header_html', models.TextField(blank=True, default='')),
                ('footer_html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('variables_schema', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Document template version',
                'verbose_name_plural': 'Document template versions',
                'ordering': ['template', 'version', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'archived'])), name='document_template_version_status_allowed'), models.UniqueConstraint(fields=('template', 'version'), name='document_template_version_unique_per_template')],
            },
        ),
    ]
