# Generated by Django 5.2.16 on 2026-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_add_template_and_version_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
