# Generated by Django 5.2.16 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_add_valid_until_to_documentinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentinstance",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="proforma_validity_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
