# Generated by Django 5.2.16 on 2026-08-04 14:29

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_contract_identity_fields'),
        ('documents', '0009_documentinstance_customer_identity_snapshot'),
        ('hahitantsoa', '0006_add_venue_and_service_models'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('CIN', 'CIN'), ('NIF', 'NIF'), ('STAT', 'STAT'), ('RCS', 'RCS'), ('Logo', 'Logo'), ('Pièce jointe email', 'Pièce jointe email'), ('Justificatif paiement', 'Justificatif paiement'), ('Reçu', 'Reçu'), ('Capture Mobile Money', 'Capture Mobile Money'), ('Copie chèque', 'Copie chèque'), ('Bordereau virement', 'Bordereau virement'), ('Preuve carte bancaire', 'Preuve carte bancaire'), ('Autre', 'Autre')], max_length=64)),
                ('file', models.FileField(upload_to=apps.documents.models.uploaded_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='customers.customer')),
                ('hahitantsoa_event_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='hahitantsoa.hahitantsoaeventdraft')),
                ('reservation_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='reservations.reservationdraft')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded attachment',
                'verbose_name_plural': 'Uploaded attachments',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', False), _connector='OR'), name='uploaded_attachment_has_owner'), models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', False), _negated=True), name='uploaded_attachment_single_reservation_scope')],
            },
        ),
    ]
