# Generated by Django 5.2.16 on 2026-08-04 15:39

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_uploadedattachment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedattachment',
            name='file',
            field=models.FileField(max_length=512, upload_to=apps.documents.models.uploaded_attachment_path),
        ),
    ]
