# Generated by Django 5.2.16 on 2026-08-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_uploadedattachment_file'),
        ('finance', '0003_financebankprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_instances', to='finance.financebankprofile'),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_rib',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='bank_swift_bic',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
