# Generated by Django 5.2.6 on 2026-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_documentinstance_amendment_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedattachment",
            name="label",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="uploadedattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("CIN", "CIN"),
                    ("Passeport", "Passeport"),
                    ("Justificatif domicile", "Justificatif domicile"),
                    ("NIF", "NIF"),
                    ("STAT", "STAT"),
                    ("RCS", "RCS"),
                    ("Logo", "Logo"),
                    ("Pièce jointe email", "Pièce jointe email"),
                    ("Justificatif paiement", "Justificatif paiement"),
                    ("Reçu", "Reçu"),
                    ("Capture Mobile Money", "Capture Mobile Money"),
                    ("Copie chèque", "Copie chèque"),
                    ("Bordereau virement", "Bordereau virement"),
                    ("Preuve carte bancaire", "Preuve carte bancaire"),
                    ("Autre", "Autre"),
                ],
                max_length=64,
            ),
        ),
    ]
