# Generated by Django 5.2.6 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0017_uploadedattachment_label_and_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentinstance",
            name="customer_contact_points_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
