# Generated by Django 5.2.17 on 2026-09-08 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_documentinstance_document_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('titan', 'Titan'), ('hahitantsoa', 'Hahitantsoa')], max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(blank=True, default='', max_length=16)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=3)),
                ('suffix_template', models.CharField(default='/{year}', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', '-year'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'year'), name='unique_brand_year_numbering_sequence')],
            },
        ),
    ]
