# Generated by Django 5.2.17 on 2026-09-14 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_numberingsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberingsequence',
            options={'ordering': ['brand', 'sequence_type', '-year']},
        ),
        migrations.RemoveConstraint(
            model_name='numberingsequence',
            name='unique_brand_year_numbering_sequence',
        ),
        migrations.AddField(
            model_name='numberingsequence',
            name='sequence_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('invoice', 'Facture'), ('delivery_note', 'Bon de sortie / livraison')], default='proforma', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='numberingsequence',
            constraint=models.UniqueConstraint(fields=('brand', 'sequence_type', 'year'), name='unique_brand_sequence_type_year'),
        ),
    ]
