# Generated by Django 5.2.16 on 2026-07-18 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifecycle_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='client', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='party_type',
            field=models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise')], default='individual', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status__in', ['prospect', 'client'])), name='customer_lifecycle_status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('party_type__in', ['individual', 'company'])), name='customer_party_type_allowed'),
        ),
    ]
