# Generated by Django 5.2.16 on 2026-07-22 20:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_lifecycle_status_customer_party_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesiredDateWaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_scope",
                    models.CharField(
                        choices=[("titan", "Titan"), ("hahitantsoa", "Hahitantsoa")],
                        max_length=16,
                    ),
                ),
                ("preferred_date_1", models.DateField(blank=True, null=True)),
                ("preferred_date_2", models.DateField(blank=True, null=True)),
                ("preferred_date_3", models.DateField(blank=True, null=True)),
                ("flexible_start", models.DateField(blank=True, null=True)),
                ("flexible_end", models.DateField(blank=True, null=True)),
                (
                    "interest_kind",
                    models.CharField(
                        choices=[
                            ("material", "Matériel"),
                            ("material_pack", "Pack matériel"),
                            ("local", "Local"),
                            ("service", "Service"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("contacted", "Contacté"),
                            ("converted", "Converti"),
                            ("lost", "Perdu"),
                            ("cancelled", "Annulé"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="desired_date_waitlist_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_desired_date_waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(quantity__gt=0),
                        name="desired_date_waitlist_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(business_scope__in=["titan", "hahitantsoa"]),
                        name="desired_date_waitlist_scope_allowed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            interest_kind__in=["material", "material_pack", "local", "service"]
                        ),
                        name="desired_date_waitlist_interest_allowed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=["new", "contacted", "converted", "lost", "cancelled"]
                        ),
                        name="desired_date_waitlist_status_allowed",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(business_scope="titan")
                            | models.Q(interest_kind__in=["material", "material_pack"])
                        ),
                        name="desired_date_waitlist_titan_interest_allowed",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                models.Q(preferred_date_1__isnull=False),
                                (
                                    models.Q(
                                        preferred_date_2__isnull=True,
                                        preferred_date_3__isnull=True,
                                    )
                                    | models.Q(
                                        preferred_date_2__isnull=False,
                                        preferred_date_3__isnull=True,
                                    )
                                    | models.Q(
                                        preferred_date_2__isnull=False,
                                        preferred_date_3__isnull=False,
                                    )
                                ),
                                flexible_start__isnull=True,
                                flexible_end__isnull=True,
                            )
                            | models.Q(
                                preferred_date_1__isnull=True,
                                preferred_date_2__isnull=True,
                                preferred_date_3__isnull=True,
                                flexible_start__isnull=False,
                                flexible_end__isnull=False,
                            )
                        ),
                        name="desired_date_waitlist_date_selection_valid",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(flexible_start__isnull=True)
                            | models.Q(flexible_end__isnull=True)
                            | models.Q(flexible_start__lte=models.F("flexible_end"))
                        ),
                        name="desired_date_waitlist_flexible_period_valid",
                    ),
                    models.CheckConstraint(
                        condition=(
                            (
                                models.Q(preferred_date_1__isnull=True)
                                | models.Q(preferred_date_2__isnull=True)
                            )
                            | ~models.Q(preferred_date_1=models.F("preferred_date_2"))
                        )
                        & (
                            (
                                models.Q(preferred_date_1__isnull=True)
                                | models.Q(preferred_date_3__isnull=True)
                            )
                            | ~models.Q(preferred_date_1=models.F("preferred_date_3"))
                        )
                        & (
                            (
                                models.Q(preferred_date_2__isnull=True)
                                | models.Q(preferred_date_3__isnull=True)
                            )
                            | ~models.Q(preferred_date_2=models.F("preferred_date_3"))
                        ),
                        name="desired_date_waitlist_preferred_dates_distinct",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(business_scope="hahitantsoa")
                            | models.Q(interest_kind__in=["local", "material", "service"])
                        ),
                        name="desired_date_waitlist_hah_interest_allowed",
                    ),
                ],
            },
        ),
    ]
