# Generated by Django 5.2.16 on 2026-08-04 15:36

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_backfill_customer_public_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='public_reference',
            field=models.CharField(db_index=True, default=apps.customers.models.generate_customer_public_reference, editable=False, max_length=24, unique=True),
        ),
    ]
