# Generated by Django 5.2.16 on 2026-08-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_prospect_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prospect_follow_up_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='prospect_status',
            field=models.CharField(blank=True, choices=[('new', 'Nouveau'), ('contact_attempted', 'Tentative de contact'), ('contacted', 'Contacté'), ('qualified', 'Qualifié'), ('proforma_sent', 'Proforma envoyée'), ('to_recall', 'À relancer'), ('converted', 'Converti en client'), ('disqualified', 'Non qualifié'), ('lost', 'Perdu')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='prospect_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prospect_status_reason',
            field=models.TextField(blank=True),
        ),
    ]
