# Generated by Django 5.2.17 on 2026-08-20 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_legacy_customer_contacts(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    CustomerContactPoint = apps.get_model("customers", "CustomerContactPoint")
    for customer in Customer.objects.exclude(email="").iterator():
        CustomerContactPoint.objects.get_or_create(
            customer_id=customer.pk,
            kind="email",
            value=customer.email.strip(),
            defaults={"is_primary": True},
        )
    for customer in Customer.objects.exclude(phone="").iterator():
        CustomerContactPoint.objects.get_or_create(
            customer_id=customer.pk,
            kind="phone",
            value=customer.phone.strip(),
            defaults={"is_primary": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_prospect_pipeline_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Téléphone')], max_length=16)),
                ('value', models.CharField(max_length=254)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer contact point',
                'verbose_name_plural': 'Customer contact points',
                'ordering': ['kind', '-is_primary', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'kind', 'value'), name='customer_contact_point_unique_value'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer', 'kind'), name='customer_contact_point_one_primary_per_kind')],
            },
        ),
        migrations.RunPython(
            copy_legacy_customer_contacts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
