# Generated by Django 5.2.15 on 2026-06-16 22:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_documentinstance_customer_and_more'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_kind', models.CharField(choices=[('deposit', 'deposit'), ('balance', 'balance'), ('caution', 'caution'), ('owner_injection', 'owner_injection'), ('investor_injection', 'investor_injection'), ('date_reservation', 'date_reservation'), ('other', 'other')], max_length=32)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('mobile_money', 'mobile_money'), ('cheque', 'cheque'), ('other', 'other')], max_length=32)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('reconciled', 'reconciled')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='documents.documentinstance')),
                ('reservation_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservationdraft')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', False), models.Q(('source_label', ''), _negated=True), _connector='OR'), name='payment_requires_reservation_or_source_label'), models.CheckConstraint(condition=models.Q(models.Q(('payment_status__in', ['confirmed', 'reconciled']), ('paid_at__isnull', False), ('receipt_document__isnull', False)), models.Q(('payment_status__in', ['confirmed', 'reconciled']), _negated=True), _connector='OR'), name='payment_confirmed_status_requires_paid_at_and_receipt'), models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False)), _connector='OR'), name='payment_confirmed_marker_consistent')],
            },
        ),
    ]
