# Generated by Django 5.2.15 on 2026-06-20 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentinstance_hahitantsoa_event_draft_and_more'),
        ('hahitantsoa', '0005_event_draft_amendment_request_line'),
        ('inventory', '0008_inventorydamagelosssettlementexecution_and_more'),
        ('payments', '0002_payment_refund_obligation'),
        ('reservations', '0006_reservationdraft_prerequisite_marker_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_requires_reservation_or_source_label',
        ),
        migrations.AddField(
            model_name='payment',
            name='hahitantsoa_event_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='hahitantsoa.hahitantsoaeventdraft'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', False), models.Q(('source_label', ''), _negated=True), _connector='OR'), name='payment_requires_reservation_or_source_label'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_draft__isnull', False), ('hahitantsoa_event_draft__isnull', False), _negated=True), name='payment_single_draft_link'),
        ),
    ]
