# Generated by Django 5.2.16 on 2026-07-23 02:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financial_categories'),
        ('payments', '0004_payment_billing_refund_obligation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliationImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('committed', 'Committed')], default='staged', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reconciliation_imports', to='finance.financeaccount')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReconciliationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_reference', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('raw_data', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('reconciled', 'Reconciled')], default='staged', max_length=16)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_decision', models.CharField(blank=True, max_length=500)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reconciliation_lines', to='finance.financeaccount')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payments.paymentreconciliationimport')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReconciliationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_allocations', to='payments.payment')),
                ('statement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.paymentreconciliationline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationimport',
            constraint=models.UniqueConstraint(fields=('account', 'content_fingerprint'), name='payment_reconciliation_import_fingerprint_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationimport',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='payment_reconciliation_import_commit_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_reconciliation_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationline',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', Decimal('0.00'))), name='payment_reconciliation_line_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationline',
            constraint=models.UniqueConstraint(fields=('account', 'fingerprint'), name='payment_reconciliation_line_fingerprint_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_reconciliation_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationallocation',
            constraint=models.UniqueConstraint(fields=('statement_line', 'payment'), name='payment_reconciliation_line_payment_unique'),
        ),
    ]
