# Generated by Django 5.2.17 on 2026-08-26 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_billinginvoice_hahitantsoa_event_draft"),
        ("documents", "0018_documentinstance_customer_contact_points_snapshot"),
        ("hahitantsoa", "0009_hahitantsoacommercialterms_and_more"),
        ("inventory", "0007_hahitantsoa_event_draft_stock"),
        ("payments", "0005_paymentreconciliationimport_and_more"),
        ("reservations", "0010_reservationdraftamendment_versioning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="deposit_recording_idempotency_key",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reservation_draft__isnull", False),
                    models.Q(("deposit_recording_idempotency_key", ""), _negated=True),
                ),
                fields=("reservation_draft", "deposit_recording_idempotency_key"),
                name="payment_titan_deposit_recording_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("hahitantsoa_event_draft__isnull", False),
                    models.Q(("deposit_recording_idempotency_key", ""), _negated=True),
                ),
                fields=("hahitantsoa_event_draft", "deposit_recording_idempotency_key"),
                name="payment_hahitantsoa_deposit_recording_idempotency_unique",
            ),
        ),
    ]
