# Generated by Django 5.2.17 on 2026-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_deposit_recording_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('virement', 'virement'), ('mobile_money', 'mobile_money'), ('mvola', 'mvola'), ('orange_money', 'orange_money'), ('taptap_send', 'taptap_send'), ('versement', 'versement'), ('cheque', 'cheque'), ('other', 'other')], max_length=32),
        ),
    ]
