# Generated by Django 5.2.17 on 2026-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_bank_name_payment_check_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_kind',
            field=models.CharField(
                choices=[
                    ('deposit', 'deposit'),
                    ('balance', 'balance'),
                    ('caution', 'caution'),
                    ('night_security', 'night_security'),
                    ('owner_injection', 'owner_injection'),
                    ('investor_injection', 'investor_injection'),
                    ('date_reservation', 'date_reservation'),
                    ('refund', 'refund'),
                    ('other', 'other'),
                ],
                max_length=32,
            ),
        ),
    ]
