# Generated by Django 5.2.15 on 2026-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttemptBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("account", "Account"),
                            ("account_peer", "Account and transport peer"),
                            ("transport_peer", "Transport peer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Login attempt bucket",
                "verbose_name_plural": "Login attempt buckets",
                "ordering": ["key"],
            },
        ),
    ]
